//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.ExtranetResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.ExtranetResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept conditions.
        /// </summary>
        public static string AcceptConditions {
            get {
                return ResourceManager.GetString("AcceptConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmercadoverde garantiza que tratará los datos personales cumpliendo lo establecidos en la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal (LOPD), Real Decreto 1720/2007, de 21 de diciembre, por el que se aprueba el Reglamento de desarrollo de la Ley Orgánica 15/1999 (RLOPD), y legislación en materia de servicios de la sociedad de la información y de comercio electrónico (LSSICE). A tal efecto, se han adoptado las medidas de carácter técnico y organizativo de seguridad  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AcceptConditionsText {
            get {
                return ResourceManager.GetString("AcceptConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add you first store!.
        /// </summary>
        public static string AddFirstStore {
            get {
                return ResourceManager.GetString("AddFirstStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New store.
        /// </summary>
        public static string AddStore {
            get {
                return ResourceManager.GetString("AddStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your brands.
        /// </summary>
        public static string BrandList {
            get {
                return ResourceManager.GetString("BrandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse images.
        /// </summary>
        public static string BrowseImages {
            get {
                return ResourceManager.GetString("BrowseImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change registration data.
        /// </summary>
        public static string ChangeRegistrationData {
            get {
                return ResourceManager.GetString("ChangeRegistrationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacta con Nosotros!.
        /// </summary>
        public static string ContactWithUs {
            get {
                return ResourceManager.GetString("ContactWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Information.
        /// </summary>
        public static string CookieInformation {
            get {
                return ResourceManager.GetString("CookieInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .© 2016 Poblamarket™ All rights reserved..
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete file.
        /// </summary>
        public static string CouldNotDeleteFile {
            get {
                return ResourceManager.GetString("CouldNotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Get Uploaded File.
        /// </summary>
        public static string CouldNotGetUploadedFile {
            get {
                return ResourceManager.GetString("CouldNotGetUploadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateBrand.
        /// </summary>
        public static string CreateBrand {
            get {
                return ResourceManager.GetString("CreateBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describite.
        /// </summary>
        public static string DescriptionAboutYou {
            get {
                return ResourceManager.GetString("DescriptionAboutYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airbnb se basa en las relaciones personales. Ayuda a otros usuarios a conocerte un poco mejor.&lt;br&gt;&lt;br&gt; Incluso puedes entrar en aspectos más personales: ¿Hay alguna frase en especial que defina tu forma de ver la vida?.
        /// </summary>
        public static string DescriptionAboutYouText {
            get {
                return ResourceManager.GetString("DescriptionAboutYouText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant delete the post, it is published.
        /// </summary>
        public static string DontDeletePublishPost {
            get {
                return ResourceManager.GetString("DontDeletePublishPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant delete the store, it is published.
        /// </summary>
        public static string DontDeletePublishStore {
            get {
                return ResourceManager.GetString("DontDeletePublishStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont do the action.
        /// </summary>
        public static string DontDoAction {
            get {
                return ResourceManager.GetString("DontDoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password.
        /// </summary>
        public static string EnterYourCurrentPassword {
            get {
                return ResourceManager.GetString("EnterYourCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General data.
        /// </summary>
        public static string GeneralData {
            get {
                return ResourceManager.GetString("GeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General info.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you got store?.
        /// </summary>
        public static string HaveStore {
            get {
                return ResourceManager.GetString("HaveStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we had a problem and we can&apos;t do it the accition..
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is published.
        /// </summary>
        public static string IsPublished {
            get {
                return ResourceManager.GetString("IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last activity.
        /// </summary>
        public static string LastActivity {
            get {
                return ResourceManager.GetString("LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal information.
        /// </summary>
        public static string LegalInformation {
            get {
                return ResourceManager.GetString("LegalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and see your stores and comments!.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member since.
        /// </summary>
        public static string MemberSince {
            get {
                return ResourceManager.GetString("MemberSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password saved correctly .
        /// </summary>
        public static string NewPasswordSaved {
            get {
                return ResourceManager.GetString("NewPasswordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not File To Upload.
        /// </summary>
        public static string NotFileToUpload {
            get {
                return ResourceManager.GetString("NotFileToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours.
        /// </summary>
        public static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is not valid.
        /// </summary>
        public static string PasswordNotValid {
            get {
                return ResourceManager.GetString("PasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password or user are not valid.
        /// </summary>
        public static string PasswordOrUserNotValid {
            get {
                return ResourceManager.GetString("PasswordOrUserNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Register.
        /// </summary>
        public static string PleaseRegister {
            get {
                return ResourceManager.GetString("PleaseRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquí podrás escribir artículos, por ejemplo como hacéis vuestros productos, o articulos relacionados con vuestro trabajo, esto dara mayor visibilidad a vuestra tienda tanto en la página como en internet. A parte de ayudarnos a promocionar y concienciar a las personas el consumir productos sostenibles y conociendo su origen..
        /// </summary>
        public static string PostExplainText1 {
            get {
                return ResourceManager.GetString("PostExplainText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una vez haya terminado de escribir el post y decidad publicarlo, revisaremos y puede ser que modifiquemos el texto para que se vea correctamente en la web..
        /// </summary>
        public static string PostExplainText2 {
            get {
                return ResourceManager.GetString("PostExplainText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasf sadf asdf dsa f asdf sadf asdf asd fasd f sadf sa fsad f asdf as df.
        /// </summary>
        public static string PostHelpInfo {
            get {
                return ResourceManager.GetString("PostHelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of posts.
        /// </summary>
        public static string PostList {
            get {
                return ResourceManager.GetString("PostList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post was published.
        /// </summary>
        public static string PostPublished {
            get {
                return ResourceManager.GetString("PostPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private rules.
        /// </summary>
        public static string PrivateInformation {
            get {
                return ResourceManager.GetString("PrivateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish post.
        /// </summary>
        public static string PublishPost {
            get {
                return ResourceManager.GetString("PublishPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your email and you will received a new password.
        /// </summary>
        public static string RecoverPasswordText {
            get {
                return ResourceManager.GetString("RecoverPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign In.
        /// </summary>
        public static string RegisterPlease {
            get {
                return ResourceManager.GetString("RegisterPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register like a new user.
        /// </summary>
        public static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string RepeatNewPasword {
            get {
                return ResourceManager.GetString("RepeatNewPasword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return login.
        /// </summary>
        public static string ReturnLogin {
            get {
                return ResourceManager.GetString("ReturnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We reviewed the post before publishing.
        /// </summary>
        public static string ReviewedPostBeforePublishing {
            get {
                return ResourceManager.GetString("ReviewedPostBeforePublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised.
        /// </summary>
        public static string Revised {
            get {
                return ResourceManager.GetString("Revised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved correctly!!.
        /// </summary>
        public static string SaveOk {
            get {
                return ResourceManager.GetString("SaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See you store!.
        /// </summary>
        public static string SeeYouStore {
            get {
                return ResourceManager.GetString("SeeYouStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select area.
        /// </summary>
        public static string SelectArea {
            get {
                return ResourceManager.GetString("SelectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected country.
        /// </summary>
        public static string SelectedCountry {
            get {
                return ResourceManager.GetString("SelectedCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected language.
        /// </summary>
        public static string SelectedLanguage {
            get {
                return ResourceManager.GetString("SelectedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile photo.
        /// </summary>
        public static string SelectProfilePhoto {
            get {
                return ResourceManager.GetString("SelectProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your stores.
        /// </summary>
        public static string StoreList {
            get {
                return ResourceManager.GetString("StoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to our newsletter.
        /// </summary>
        public static string SubscribeOur {
            get {
                return ResourceManager.GetString("SubscribeOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suegerenia, duda o hasta crítica!.
        /// </summary>
        public static string TellMeUs {
            get {
                return ResourceManager.GetString("TellMeUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms of use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text is too short..
        /// </summary>
        public static string TextTooShort {
            get {
                return ResourceManager.GetString("TextTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introudce un horario, puedes copiar este formato y sustituir la fechas:
        ///                                        Lunes - Viernes : 10:00 - 14:00 a 16:00 - 20:00 
        ///                                        Sabdao: 10:00 - 22:00.
        /// </summary>
        public static string TimeTableExample {
            get {
                return ResourceManager.GetString("TimeTableExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadImage.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user exist.
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exits.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Url.
        /// </summary>
        public static string WebUrl {
            get {
                return ResourceManager.GetString("WebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome!.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We send activation mail..
        /// </summary>
        public static string WeSendActivationMail {
            get {
                return ResourceManager.GetString("WeSendActivationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We send a mail with your password.
        /// </summary>
        public static string WeSendMailWithYouPassword {
            get {
                return ResourceManager.GetString("WeSendMailWithYouPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who we are.
        /// </summary>
        public static string WhoInformation {
            get {
                return ResourceManager.GetString("WhoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write you first post!.
        /// </summary>
        public static string WriteFirstPost {
            get {
                return ResourceManager.GetString("WriteFirstPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a post!.
        /// </summary>
        public static string WritePost {
            get {
                return ResourceManager.GetString("WritePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the conditions.
        /// </summary>
        public static string YouMustAcceptConditions {
            get {
                return ResourceManager.GetString("YouMustAcceptConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must complete all required fields.
        /// </summary>
        public static string YouMustCompleteRequiredFields {
            get {
                return ResourceManager.GetString("YouMustCompleteRequiredFields", resourceCulture);
            }
        }
    }
}
