CREATE TABLE [dbo].[TblUser] (
    [IdUser]                 INT		    IDENTITY(1,1) NOT NULL,
    [Name]                   NVARCHAR (MAX) NULL,
    [Surname]                NVARCHAR (MAX) NULL,
    [Email]                  NVARCHAR (MAX) NOT NULL,
	[Password]               NVARCHAR (150) NOT NULL,
    [PostalCode]             NVARCHAR (MAX) NULL,
    [CreationDate]           DATETIME       NULL,
	[UrlWebSite]       NVARCHAR (250) NULL,
    [Published]              BIT            NOT NULL,
    [LastActivity]           DATETIME       NULL,
    [LastLogin]              DATETIME       NULL,
    [IsCompany]              BIT            NULL,
    [AcceptedConditions]     BIT            NULL,
    [AcceptedConditionsDate] DATETIME       NULL,
    [RegistrationDate]       DATETIME       NULL,
    [LanguageId] INT NULL, 
	[Street]                 NVARCHAR (250) NULL,
    [NumberStreet]           NVARCHAR (50)  NULL,
    [CityName]               NVARCHAR (50)  NULL,
    [BirthDate]              DATETIME       NULL,
    [Description] NVARCHAR(MAX) NULL, 
    [Photo] NVARCHAR(150) NULL,
    [CountryId] INT NULL, 
    [MailActivation] BIT NULL, 
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([IdUser] ASC), 
    CONSTRAINT [FK_TblUser_TbkLanguage] FOREIGN KEY ([LanguageId]) REFERENCES [TblLanguage]([IdLanguage]), 
    CONSTRAINT [FK_TblUser_ToTblCountry] FOREIGN KEY ([CountryId]) REFERENCES [TblCountry]([IdCountry])
);

